services:
  desktop:
    #image: lscr.io/linuxserver/chrome:latest
    container_name: desktop
    build: 
      context: .
      network: host
      dockerfile: Dockerfile
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
      - PASSWORD=123
      - CHROME_CLI=https://www.google.de/
    volumes:
      - /opt/docker_data/desktop/config:/config
    ports:
      - "127.0.0.1:9001:3001"
    shm_size: "1gb"
    restart: unless-stopped
